name: teachent_app
description: A new Flutter project.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  build_runner: ^2.1.8
  cupertino_icons: ^1.0.2
  firebase_core: ^1.13.1
  firebase_database: ^9.0.8
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  hive: ^2.1.0
  hive_flutter: ^1.1.0
  hive_generator: ^1.1.2
  intl: ^0.17.0
  bcrypt: ^1.1.3
  mockito: ^5.2.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_launcher_icons: ^0.9.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/app_logo.png

flutter_icons:
  android: true
  image_path: "assets/app_logo.png"
